Python. Homework #1. Task #1.  Serheyuk Agnia
hugnia/pythonHomework pull request #1
Opened 2022-03-07 11:08 UTC by hugnia

hopefully, I did it right, but I'm not sure. Im sorry for my github skills

2022-03-10 15:52 UTC, SpirinEgor requested changes

2022-03-10 15:52 UTC, SpirinEgor commented on .github/workflows/main.yaml
> +- name: Install dependencies
That doesn't look write :( 
And you can see that there is no actions for that PR (no green check mark at the commit and Action tab is empty).

I suggest you to look at this [repo](https://github.com/JetBrains-Research/embeddings-for-trees). There are examples with creating CI workflow and folder structure.

2022-03-10 15:52 UTC, SpirinEgor commented on requirements.txt
> +mypy==0.910
Probably pytest should be specified too, AFAIK it is not from standard library

2022-03-19 09:36 UTC, hugnia commented
Ok, I guess, I figured out how to write the CI file. 
Are tests failed because there are none of them in the folder at the moment? 
Are any changes needed?

2022-03-22 09:48 UTC, SpirinEgor approved these changes

2022-03-22 09:48 UTC, merged